version: '2'
services:
  myerp.db:
    image: postgres:9.5
    ports:
      - "127.0.0.1:9032:5432"
    volumes:
#       - "./data/db:/var/lib/postgresql/data"
       - "COPY ./init/db/docker-entrypoint-initdb.d /docker-entrypoint-initdb.d"
        
    environment:
      - POSTGRES_DB=db_myerp
      - POSTGRES_USER=usr_myerp
      - POSTGRES_PASSWORD=myerp
      
